### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 64: ordinal not in range(128)

### ISSUE THREAD

**Issue by smarie** [eddieantonio/sentinel#3]
Apparently this error happens during installation on ubuntu docker image when language pack is not installed. 

See https://github.com/smarie/python-pyfields/issues/42 for details

**Comment by smarie** [comment]
Could it be caused by the `©` character in the header of `sentinel.py` ?

**Comment by eddieantonio** [comment]
Thank you for the bug report!

This happens in the `setup.py`. The README was being read in the default encoding, when it should always be read in UTF-8. The Ubuntu locale stuff changes the default encoding to UTF-8, which makes the install work again. I've changed the setup.py to explicity open the README in UTF-8, and you can get it here:

https://pypi.org/project/sentinel/0.1.2/

**Comment by smarie** [comment]
Cool, this is extremely fast ! thanks! (and cool lib by the way :) )
